// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Sebastian Torres, Sebastian Alfonso",
            "url": "https://github.com/sebastiantorreslab/desafiofinal-turnos/tree/main"
        },
        "license": {
            "name": "Digital House",
            "url": "https://www.digitalhouse.com/co?utm_source=Google\u0026utm_medium=paidsearch\u0026utm_campaign=Clic\u0026utm_term=Institucional\u0026utm_content=institucional-institucional-branding-home-adresponsive-awareness-brandkws-none-exactas-adtext-none-exactas-ad1-latam-search\u0026gad_source=1\u0026gclid=CjwKCAjwh4-wBhB3EiwAeJsppJ2OfeYOwheVflmB-kJD2ctgZIZwplWV89rVP21dChHQdJtreVHUZRoCzOsQAvD_BwE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/dentists": {
            "get": {
                "description": "Recupera una lista de todos los dentistas registrados",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dentists"
                ],
                "summary": "Obtiene todos los dentistas",
                "responses": {
                    "200": {
                        "description": "Lista de dentistas",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Dentist"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Crea un nuevo dentista con los datos proporcionados",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dentists"
                ],
                "summary": "Crea un nuevo dentista",
                "parameters": [
                    {
                        "description": "Datos del Dentista",
                        "name": "dentist",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Dentist"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Dentista creado",
                        "schema": {
                            "$ref": "#/definitions/domain.Dentist"
                        }
                    }
                }
            }
        },
        "/dentists/{id}": {
            "get": {
                "description": "Recupera los detalles de un dentista por su ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dentists"
                ],
                "summary": "Obtiene un dentista por ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del Dentista",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Detalles del dentista",
                        "schema": {
                            "$ref": "#/definitions/domain.Dentist"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Actualiza los datos de un dentista con la información proporcionada",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dentists"
                ],
                "summary": "Actualiza los datos de un dentista",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del Dentista",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos del Dentista a actualizar",
                        "name": "dentist",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Dentist"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Dentista actualizado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/domain.Dentist"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Elimina un dentista del sistema por su ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dentists"
                ],
                "summary": "Elimina un dentista",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del Dentista",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Mensaje de confirmación de eliminación",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/dentists/{id}/fields": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Actualiza uno o más campos específicos de un dentista",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "dentists"
                ],
                "summary": "Actualiza campos específicos de un dentista",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del Dentista",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Dentista actualizado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/domain.Dentist"
                        }
                    }
                }
            }
        },
        "/patients": {
            "get": {
                "description": "Recupera una lista de todos los pacientes registrados en el sistema",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "patients"
                ],
                "summary": "Obtiene todos los pacientes",
                "responses": {
                    "200": {
                        "description": "Lista de pacientes",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Patient"
                            }
                        }
                    },
                    "400": {
                        "description": "Solicitud incorrecta",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Crea un nuevo paciente con los datos proporcionados",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "patients"
                ],
                "summary": "Crea un nuevo paciente",
                "parameters": [
                    {
                        "description": "Datos del Paciente",
                        "name": "patient",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Patient"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Paciente creado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/domain.Patient"
                        }
                    },
                    "400": {
                        "description": "Solicitud incorrecta",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "500": {
                        "description": "Error interno del servidor",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/patients/{id}": {
            "get": {
                "description": "Recupera los detalles de un paciente por su ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "patients"
                ],
                "summary": "Obtiene los detalles de un paciente específico",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del Paciente",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Detalles del paciente",
                        "schema": {
                            "$ref": "#/definitions/domain.Patient"
                        }
                    },
                    "404": {
                        "description": "Paciente no encontrado",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Actualiza los datos de un paciente con la información proporcionada",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "patients"
                ],
                "summary": "Actualiza los datos de un paciente",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del Paciente",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos actualizados del Paciente",
                        "name": "patient",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Patient"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Paciente actualizado exitosamente",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Solicitud incorrecta",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "Paciente no encontrado",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Elimina un paciente del sistema",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "patients"
                ],
                "summary": "Elimina un paciente",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del Paciente",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Mensaje de confirmación",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "404": {
                        "description": "Paciente no encontrado",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/patients/{id}/fields": {
            "patch": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Actualiza uno o más campos de un paciente sin necesidad de enviar toda la información",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "patients"
                ],
                "summary": "Actualiza campos específicos de un paciente",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del Paciente",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Paciente actualizado exitosamente",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "400": {
                        "description": "Solicitud incorrecta",
                        "schema": {
                            "type": "object"
                        }
                    },
                    "404": {
                        "description": "Paciente no encontrado",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        },
        "/shifts": {
            "get": {
                "description": "Recupera una lista de todos los turnos registrados",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shifts"
                ],
                "summary": "Obtiene todos los turnos",
                "responses": {
                    "200": {
                        "description": "Lista de turnos",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.Shift"
                            }
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Crea un nuevo turno con los datos proporcionados",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shifts"
                ],
                "summary": "Crea un nuevo turno",
                "parameters": [
                    {
                        "description": "Datos del Turno",
                        "name": "shift",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Shift"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Turno creado",
                        "schema": {
                            "$ref": "#/definitions/domain.Shift"
                        }
                    }
                }
            }
        },
        "/shifts/{id}": {
            "get": {
                "description": "Recupera los detalles de un turno por su ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shifts"
                ],
                "summary": "Obtiene los detalles de un turno",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del Turno",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Detalles del turno",
                        "schema": {
                            "$ref": "#/definitions/domain.Shift"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Actualiza los datos de un turno con la información proporcionada",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shifts"
                ],
                "summary": "Actualiza los datos de un turno",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del Turno",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Datos actualizados del Turno",
                        "name": "shift",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.Shift"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Turno actualizado exitosamente",
                        "schema": {
                            "$ref": "#/definitions/domain.Shift"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "description": "Elimina un turno del sistema por su ID",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "shifts"
                ],
                "summary": "Elimina un turno",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID del Turno",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Mensaje de confirmación de eliminación",
                        "schema": {
                            "type": "object"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.Dentist": {
            "type": "object",
            "required": [
                "last_name",
                "license",
                "name"
            ],
            "properties": {
                "ID": {
                    "type": "integer"
                },
                "last_name": {
                    "type": "string"
                },
                "license": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "domain.Patient": {
            "type": "object",
            "required": [
                "DNI",
                "address",
                "admission_date",
                "last_name",
                "name"
            ],
            "properties": {
                "DNI": {
                    "type": "integer"
                },
                "ID": {
                    "type": "integer"
                },
                "address": {
                    "type": "string"
                },
                "admission_date": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "domain.Shift": {
            "type": "object",
            "required": [
                "id_dentist",
                "id_patient",
                "shift_date",
                "shift_hour"
            ],
            "properties": {
                "ID": {
                    "type": "integer"
                },
                "id_dentist": {
                    "type": "integer"
                },
                "id_patient": {
                    "type": "integer"
                },
                "shift_date": {
                    "type": "string"
                },
                "shift_hour": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "3.0",
	Host:             "localhost:8080",
	BasePath:         "/api",
	Schemes:          []string{},
	Title:            "Desafío integrador Golang",
	Description:      "Sistema de reserva de turnos para odontologos y pacientes",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
